services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - lostcities-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./localhost+1.pem:/app/localhost+1.pem
      - ./localhost+1-key.pem:/app/localhost+1-key.pem
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lostcities-network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/02_test_scores.sql:/docker-entrypoint-initdb.d/02_test_scores.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lostcities"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lostcities-network

  #nginx:
  #  image: nginx:latest
  #  ports:
  #    - "443:443"
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./localhost+1.pem:/etc/ssl/localhost+1.pem:ro
  #    - ./localhost+1-key.pem:/etc/ssl/localhost+1-key.pem:ro
  #  depends_on:
  #    - frontend
  #    - backend
  #  networks:
  #    - lostcities-network

volumes:
  db-data:

networks:
  lostcities-network: