services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - lostcities-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lostcities-network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lostcities"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lostcities-network

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./localhost.crt:/etc/ssl/localhost.crt:ro
      - ./localhost.key:/etc/ssl/localhost.key:ro
    depends_on:
      - frontend
      - backend
    networks:
      - lostcities-network

volumes:
  db-data:

networks:
  lostcities-network: