name: CI/CD Pipeline for Deployment in Polyech's Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Build Docker images
    - name: Build backend image
      run: docker build -t backend ./backend

    - name: Build frontend image
      run: docker build -t frontend ./frontend

    - name: Build database image
      run: docker build -t database ./database

    # 4. Start services for testing
    - name: Start services
      run: docker-compose up -d

    # 5. Set up Deno
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v1.29.0

    # 6. Set API_URL for testing
    - name: Set environment variable for API_URL
      run: echo "API_URL=https://lostcitiesbackend.onrender.com" >> $GITHUB_ENV

    # 7. Run backend tests with Deno
    - name: Run backend tests
      run: deno test --allow-net --allow-env --allow-read

    # 8. Stop services after testing
    - name: Stop services
      run: docker-compose down

#  deploy:
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Setup SSH key
#        uses: webfactory/ssh-agent@v0.7.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Deploy to school server via SSH
#        run: |
#          ssh -o StrictHostKeyChecking=no USERNAME@SERVER_ADDRESS << 'EOF'
#            cd /home/USERNAME/mon-projet  # ← à adapter avec le bon chemin sur le serveur
#            git pull origin main
#            docker-compose down
#            docker-compose up --build -d
#          EOF
